### ISSUE TITLE
Test failures on OpenJDK 10.0.2

### ISSUE THREAD

**Issue by mmjb** [acr31/features-javac#2]
Tried `mvn test`.

Environment: Ubuntu 18.04; OpenJDK 10.0.2

Expected Outcome: Things work.

Actual Outcome:
```
Running uk.ac.cam.acr31.features.javac.SymbolScannerTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.379 sec
Running uk.ac.cam.acr31.features.javac.FeaturePluginTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.559 sec
Running uk.ac.cam.acr31.features.javac.ComputedFromTest
Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.603 sec <<< FAILURE!
computedFrom_excludesAnonymousParameters(uk.ac.cam.acr31.features.javac.ComputedFromTest)  Time elapsed: 0.193 sec  <<< ERROR!
java.lang.NullPointerException
	at uk.ac.cam.acr31.features.javac.graph.FeatureGraph.toIdentifierNode(FeatureGraph.java:187)
	at uk.ac.cam.acr31.features.javac.syntactic.SymbolScanner.addNode(SymbolScanner.java:104)
	at uk.ac.cam.acr31.features.javac.syntactic.SymbolScanner.visitVariable(SymbolScanner.java:88)
	at uk.ac.cam.acr31.features.javac.syntactic.SymbolScanner.visitVariable(SymbolScanner.java:37)
[...]
```

**Comment by acr31** [comment]
Fixed in ea1cefad3cb2e0d4ec9697ae02fb1d80eb206b29. I had neglected to push this.
